server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul
zuul:
  ignoredServices: '*'
  routes:
    company:
      path: /u/**
      serviceId: company
    oauth:
        path: /o/**
        serviceId: oauth
    user:
        path: /ceshi/**
        serviceId: user