server:
  port: 8095
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: mqserver
#  rabbitmq:
#    host: 182.254.221.85
#    port: 5672
#    username: guest
#    password: StrongPassword
#    virtual-host: mq
