server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: user
  redis:
    host: 182.254.221.85
    password: redis_6379
    port: 6379
    timeout: 5000
feign:
  hystrix:
    enabled: true
